# docker build -t ubuntu20 .
# sudo docker run --net=host --privileged -it ubuntu20 /bin/bash


FROM ubuntu:20.04

# SHELL ["/bin/bash", "-c"]

# RUN apt-get update \
#     && apt-get install -y git

# RUN apt-get install -y bluez

# ### mv
# WORKDIR /opt

CMD ["sleep","1000"]
